#!/bin/sh
#
# Start the pyBus iBus to mpd interface
#

case "$1" in
  start)
 	echo "Starting iBus-mpd interface service ..."
	python -m pybus &
	;;
  stop)
	echo -n "Stopping iBus-mpd interface service..."
	pid=`ps -ef | grep 'python -m pybus' | awk '{ print $2 }'`
  echo $pid
  kill $pid
  sleep 2
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

